/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string = string> extends Record<string, unknown> {
      StaticRoutes: `/` | `/(admin)` | `/(admin)/announcement` | `/(admin)/community` | `/(admin)/expense` | `/(admin)/tours` | `/(tabs)` | `/(tabs)/` | `/(tabs)/community` | `/(tabs)/mytours` | `/(tabs)/notifications` | `/Menu` | `/_sitemap` | `/about` | `/addBusImg` | `/addHotelImg` | `/addMember` | `/addRoles` | `/addTourCheckPoints` | `/addTourImgs` | `/addTourTransportInfo` | `/addTours` | `/announcement` | `/community` | `/contact` | `/editProfile` | `/expense` | `/form` | `/login` | `/mytours` | `/notification` | `/notifications` | `/offline` | `/payment` | `/privacyPolicy` | `/profile` | `/temp` | `/terms` | `/tourmates` | `/tours` | `/updateProfile`;
      DynamicRoutes: `/(addTourDetails)/RoomAllocation/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/accomodation/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/addAccomodationForm/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/addBoardingPoint/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/addTransportDetails/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/allocatedCoordinators/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/checkPoints/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/createCheckpoints/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/exportDetails/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/guestsEnrolled/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/includedNotIncluded/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/luggage/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/myNotes/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/showAccomodationDetails/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/tourDetails/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/transportDetails/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/transportation/${Router.SingleRoutePart<T>}` | `/(addTourDetails)/viewCheckIns/${Router.SingleRoutePart<T>}` | `/RoomAllocation/${Router.SingleRoutePart<T>}` | `/accomodation/${Router.SingleRoutePart<T>}` | `/addAccomodationForm/${Router.SingleRoutePart<T>}` | `/addBoardingPoint/${Router.SingleRoutePart<T>}` | `/addTransportDetails/${Router.SingleRoutePart<T>}` | `/allocatedCoordinators/${Router.SingleRoutePart<T>}` | `/bus-mates/${Router.SingleRoutePart<T>}` | `/checkPoints/${Router.SingleRoutePart<T>}` | `/createCheckpoints/${Router.SingleRoutePart<T>}` | `/details/${Router.SingleRoutePart<T>}` | `/exportDetails/${Router.SingleRoutePart<T>}` | `/guestsEnrolled/${Router.SingleRoutePart<T>}` | `/includedNotIncluded/${Router.SingleRoutePart<T>}` | `/luggage/${Router.SingleRoutePart<T>}` | `/myNotes/${Router.SingleRoutePart<T>}` | `/mytour/${Router.SingleRoutePart<T>}` | `/postdetails/${Router.SingleRoutePart<T>}` | `/room-mates/${Router.SingleRoutePart<T>}` | `/showAccomodationDetails/${Router.SingleRoutePart<T>}` | `/tour/${Router.SingleRoutePart<T>}` | `/tourDetails/${Router.SingleRoutePart<T>}` | `/transportDetails/${Router.SingleRoutePart<T>}` | `/transportation/${Router.SingleRoutePart<T>}` | `/viewCheckIns/${Router.SingleRoutePart<T>}`;
      DynamicRouteTemplate: `/(addTourDetails)/RoomAllocation/[id]` | `/(addTourDetails)/accomodation/[id]` | `/(addTourDetails)/addAccomodationForm/[id]` | `/(addTourDetails)/addBoardingPoint/[id]` | `/(addTourDetails)/addTransportDetails/[id]` | `/(addTourDetails)/allocatedCoordinators/[id]` | `/(addTourDetails)/checkPoints/[id]` | `/(addTourDetails)/createCheckpoints/[id]` | `/(addTourDetails)/exportDetails/[id]` | `/(addTourDetails)/guestsEnrolled/[id]` | `/(addTourDetails)/includedNotIncluded/[id]` | `/(addTourDetails)/luggage/[id]` | `/(addTourDetails)/myNotes/[id]` | `/(addTourDetails)/showAccomodationDetails/[id]` | `/(addTourDetails)/tourDetails/[id]` | `/(addTourDetails)/transportDetails/[id]` | `/(addTourDetails)/transportation/[id]` | `/(addTourDetails)/viewCheckIns/[id]` | `/RoomAllocation/[id]` | `/accomodation/[id]` | `/addAccomodationForm/[id]` | `/addBoardingPoint/[id]` | `/addTransportDetails/[id]` | `/allocatedCoordinators/[id]` | `/bus-mates/[id]` | `/checkPoints/[id]` | `/createCheckpoints/[id]` | `/details/[id]` | `/exportDetails/[id]` | `/guestsEnrolled/[id]` | `/includedNotIncluded/[id]` | `/luggage/[id]` | `/myNotes/[id]` | `/mytour/[id]` | `/postdetails/[id]` | `/room-mates/[id]` | `/showAccomodationDetails/[id]` | `/tour/[id]` | `/tourDetails/[id]` | `/transportDetails/[id]` | `/transportation/[id]` | `/viewCheckIns/[id]`;
    }
  }
}
